### PR TITLE
refactor of the plugins section

### PR DESCRIPTION
**Pull request by gnmearacaun**
There was some duplication in this section and the structure was slightly confusing. I renamed the files so as to keep the structure of the old filenames as I don't know how links are rendered, or whether I would have permission to rename pages on the site.

### CODE REVIEW

**Comment by rebuilt** [comment]
Can you add the uninstall section back in?  If someone installs dashboard but then changes their mind and sets dashboard.active to false, it will keep showing up.  The only way to remove it is to run :PackerClean

**Comment by gnmearacaun** [comment]
> Can you add the uninstall section back in? If someone installs dashboard but then changes their mind and sets dashboard.active to false, it will keep showing up. The only way to remove it is to run :PackerClean
I moved 'remove plugins' to a better place as suggested. I reorganized the order of the plugins, added links and blurb to titles. Also a community section for other's lunar modules.

**Comment by rebuilt** [comment]
When you make a new page, it needs to be a markdown file.  Otherwise they won't show up as links in the sidebar.  Thanks for your work on this pr.  You've been a big help in improving the docs site.

**Comment by gnmearacaun** [comment]
Ah yeah, my bad. Great, I'm glad it helped!

**Pull request merged**
