### PR TITLE
feat: spell checking github action

### LINKED ISSUE #226: ​[Hacktoberfest] add some CI for typos in the docs repo
see title

### PR DESCRIPTION
**Pull request by LostNeophyte**
fixes #226 

adds [check-spelling](https://github.com/check-spelling/check-spelling) github action,
a list of allowed words
ignore patterns for lua tables, strings, urls, markdown `code`
fixes spelling mistakes

you can see it in action [here](https://github.com/LostNeophyte/lunarvim.org/actions/runs/3546310725)

### CODE REVIEW

**Comment by kylo252** [comment]
> you can see it in action [here](https://github.com/LostNeophyte/lunarvim.org/actions/runs/3546310725)

any idea why it's generating warnings?

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by LostNeophyte** [comment]
> > you can see it in action [here](https://github.com/LostNeophyte/lunarvim.org/actions/runs/3546310725)
> 
> any idea why it's generating warnings?
> 
> > The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

It's because of [this](https://github.com/check-spelling/check-spelling/blob/729687234a293e0680b12ca055a02fff415da89d/unknown-words.sh#L1324), `check-spelling` is using a deprecated way of sending messages. The deprecation is kinda recent, it's from October, they have time to June 2023 to switch to the new way, I didn't see an issue open on their github about this, I guess we can do that

**Comment by LostNeophyte** [comment]
opened: https://github.com/check-spelling/check-spelling/issues/37

**Comment by LostNeophyte** [comment]
updated to alpha release, no more warnings: https://github.com/LostNeophyte/lunarvim.org/actions/runs/3552934976

**Review by kylo252 — APPROVED** [review]
Thanks! 🚀

**Pull request merged**
