### PR TITLE
Add main nav for tips. Modified: configuration, keybindings, language…

### PR DESCRIPTION
**Pull request by rebuilt**
Add main nav for tips. Modified: configuration, keybindings, languages plugins, migrating from old versions, snippets

### CODE REVIEW

**Comment by rebuilt** [comment]
Oops. Looking at that lines changed count, I realize we should .gitignore package-lock.json.

**Comment by abzcoding** [comment]
> Oops. Looking at that lines changed count, I realize we should .gitignore package-lock.json.

can you add it to `.gitignore` and push the changes 🥺

**Comment by rebuilt** [comment]
Ok.  I added it to .gitignore file and then ran `git rm --cached package-lock.json`

**Review by abzcoding — APPROVED** [review]
Thank you for your wonderful work on this :pray:

**Pull request merged**
