### PR TITLE
docs: added angular docs and frameworks category

### LINKED ISSUE #145: Add documentation for setting up Angular LSP

### PR DESCRIPTION
**Pull request by olrtg**
This PR adds some documentation for the Angular framework. It also adds a new category called "Frameworks" which from now on, Vue will belong to this category aswell.

Fixes #145.

Please let me know your thoughts and if there's something else that I should do on my end so you can merge this PR.

### CODE REVIEW

**Review by vonPB — APPROVED** [review]
LGTM.
Just noticed that we have like 10 different versions of `Install Syntax Highlighting`, `Supported language servers`.... Will fix that later :)

**Comment by vonPB** [comment]
one thing that will need to be fixed is the `Landing Setup` link for vue and maybe a new one for Angular on the landing page.
@mhmdali102 is that something you could do? I don't know where you got the logos from etc

**Comment by olrtg** [comment]
@vonPB Thank you so much.. yeah also I've noticed that vue has a broken link for the manual configuration in https://www.lunarvim.org/docs/languages/vue#supported-language-servers

**Comment by mhmdali102** [comment]
@vonPB ok I'll update `Landing Setup` languages... I got most of them from devicon.dev

**Comment by olrtg** [comment]
@vonPB I think it should point to this https://www.lunarvim.org/docs/languages#server-setup

**Pull request merged**
