### PR TITLE
"Available" sounds like here's the only options

### PR DESCRIPTION
**Pull request by qvieth**

### CODE REVIEW

**Comment by abzcoding** [comment]
> _No description provided._

how about `Extra` :thinking:

**Comment by qvieth** [comment]
Yeah right, extra is even better!

**Comment by abzcoding** [comment]
> Yeah right, extra is even better!

can you update your PR :pleading_face:

**Comment by qvieth** [comment]
Done sir!!

**Comment by abzcoding** [comment]
i'll update it directly, github is acting up :angry:

**Pull request closed without merging**
