### PR TITLE
core-plugins-list

### PR DESCRIPTION
**Pull request by kylo252**

### CODE REVIEW

**Comment by kylo252** [comment]
What do you guys think of this?

cc: @abzcoding, @PasiBergman

**Comment by abzcoding** [comment]
> What do you guys think of this?
> 
> cc: @abzcoding, @PasiBergman

looks very good to me, a tiny note though, can we somehow mention that  by `bufferline` we mean `barbar` 😅

**Comment by kylo252** [comment]
> looks very good to me, a tiny note though, can we somehow mention that by `bufferline` we mean `barbar` 😅

I've actually been daily-driving it for a while and thinking about switching over, but I really miss that `BufferWipeout` from BarBar. I've tried implementing a minimal version on my own and it works fine for the most part except that it doesn't seem to switch to the buffers in next buffer in order: https://github.com/kylo252/lvim/blob/3c17a0025c8b35b9011725b5bf1643de3d62912b/lua/user/bufferline.lua#L3-L58

Do you have a solution? do you use `bbye` directly? or do you not care about this feature? 😄

**Comment by abzcoding** [comment]
> > looks very good to me, a tiny note though, can we somehow mention that by `bufferline` we mean `barbar` 😅
> 
> I've actually been daily-driving it for a while and thinking about switching over, but I really miss that `BufferWipeout` from BarBar. I've tried implementing a minimal version on my own, _based_ on https://github.com/famiu/bufdelete.nvim, and it works fine for the most part except that it doesn't seem to switch to the buffers in next buffer in order: https://github.com/kylo252/lvim/blob/3c17a0025c8b35b9011725b5bf1643de3d62912b/lua/user/bufferline.lua#L3-L58
> 
> Do you have a solution? do you use `bbye` directly? or do you not care about this feature? 😄

tbh i've never used that feature 😅

**Review by PasiBergman — APPROVED** [review]
Looks nice! Maybe we could also remove the old plugins from the Configuration chapter
- bufferline
- come

**Review by abzcoding — APPROVED** [review]
tyvm <3

**Comment by kylo252** [comment]
My attempt at using [vuetable ](https://github.com/ratiw/vuetable-2) has unfortunately failed 🥲 
I still think this is still fine, since we can generate a new `core_plugins.json` file and use whatever json->markdown converter. 

I also fixed the hyperlinks since I didn't know that we can't mix markdown and html syntax that way.

**Pull request merged**
