### PR TITLE
docs: add more info about plugins management

### PR DESCRIPTION
**Pull request by kylo252**

### CODE REVIEW

**Comment by kylo252** [comment]
Related https://github.com/LunarVim/LunarVim/issues/2476#issuecomment-1100596710

**Review by abzcoding — APPROVED** [review]
tyvm 👍

**Comment by kylo252** [comment]
Also related https://github.com/LunarVim/LunarVim/issues/2426

@danielo515, please let me know if you have any suggestions for this section, so I can update it.

**Comment by danielo515** [comment]
> Also related [LunarVim/LunarVim#2426](https://github.com/LunarVim/LunarVim/issues/2426)
> 
> @danielo515, please let me know if you have any suggestions for this section, so I can update it.

from my mobile phone it looks quite good. I'll take a look at the published version later from desktop

**Pull request merged**
