### PR TITLE
docs(example-plugins): replace nvim-ts-rainbow with maintaned fork

### PR DESCRIPTION
**Pull request by gacallea**
[CHECKLIST]

[x] I have read the [contributing guidelines](https://github.com/LunarVim/lunarvim.org/blob/master/CONTRIBUTING.md)

[x] I prefixed the title with one of the following tags:
 - docs: on documentation updates

the original plugin maintainer has archived the repo and encouraged anybody to take over. the fork replacing the original here does that egregiously. installed and working on my setup.

### CODE REVIEW

**Comment by LostNeophyte** [comment]
please edit `docs/plugins/extra-plugins.md` instead(or edit both) as the [contributing guidelines](https://github.com/LunarVim/lunarvim.org/blob/master/CONTRIBUTING.md) say

**Comment by gacallea** [comment]
> docs/plugins/extra-plugins.md

hi @LostNeophyte :)

I don't seem to have that file in my fork. Have cloned the wrong branch?

thank you for your support.

**Comment by LostNeophyte** [comment]
On master it's here, it was moved https://github.com/LunarVim/lunarvim.org/blob/master/docs/configuration/plugins/example-configurations.md

**Comment by gacallea** [comment]
it should be good now :)

**Comment by LostNeophyte** [comment]
Thanks!

**Comment by gacallea** [comment]
thank you! :)

**Pull request merged**
