### PR TITLE
docs: add ansible language + other language formatting fixes

### PR DESCRIPTION
**Pull request by Z3rio**
This adds the Ansible language to the supported languages list.

It also changes the "supported ???" lists to actual lists instead of code blocks.
Which should be easier to read & nicer looking

# Fixes issue
Issue #290 for this repo
Issue #3451 for @LunarVim/LunarVim (main repo)

### CODE REVIEW

**Comment by mhmdali102** [comment]
All great @Z3rio!
could you please fix the Ansible order alphabetically in the langauges section?

**Comment by Z3rio** [comment]
> All great @Z3rio! could you please fix the Ansible order alphabetically in the langauges section?

You mean in the "src/components/Languages/index.jsx" correct?

**Comment by Z3rio** [comment]
Like this? (check commit above)

**Comment by mhmdali102** [comment]
yes thank you!

**Pull request merged**
