### PR TITLE
Add instructions for GitHub Copilot

### PR DESCRIPTION
**Pull request by MikiVanousek**

### CODE REVIEW

**Comment by kylo252** [comment]
thanks! 

I think @abzcoding uses this, so hopefully he can provide some feedback on what works.

Related https://github.com/LunarVim/LunarVim/issues/1856

**Comment by abzcoding** [comment]
> thanks!
> 
> I think @abzcoding uses this, so hopefully he can provide some feedback on what works.
> 
> Related [LunarVim/LunarVim#1856](https://github.com/LunarVim/LunarVim/issues/1856)

I'm using https://github.com/github/copilot.vim
but nevertheless, this should work as well

**Comment by MikiVanousek** [comment]
From what I understand, copilot.lua is much faster in neovim.

**Review by abzcoding — APPROVED** [review]
just change `acording` to `according` and we are good to go

tyvm 👍

**Comment by MikiVanousek** [comment]
Alright, I believe it to be done now.

**Pull request merged**
