### PR TITLE
docs: add mini.map to extra plugins

### PR DESCRIPTION
**Pull request by gacallea**
I was soooooooo frustrated with minimap, its conflicts, and its bugs, that I seeked for an alternative for days. I finally found a GREAT ONE called mini.map :)

It works ridiculously well, it's extremley fast and lightweight, and it can double as a sidebar too! 100% Lua, no external dependencies (bar gitsigns if one wants to integrate it), and forget about wxfr brittle changes and stitches to make it compatible. it just works!!!

more rationale here: https://github.com/LunarVim/LunarVim/discussions/2838#discussioncomment-4239332

### CODE REVIEW

**Review by LostNeophyte — CHANGES_REQUESTED** [review]
This autocmd is less complicated and it works, other than that all looks good :)
```lua
lvim.autocommands = {
  {
    {"BufEnter", "Filetype"},
    {
      desc = "Open mini.map and exclude some filetypes",
      pattern = { "*" },
      callback = function()
        local exclude_ft = {
          "qf",
          "NvimTree",
          "toggleterm",
          "TelescopePrompt",
          "alpha",
          "netrw",
        }

        local map = require('mini.map')
        if vim.tbl_contains(exclude_ft, vim.o.filetype) then
          vim.b.minimap_disable = true
          map.close()
        elseif vim.o.buftype == "" then
          map.open()
        end
      end,
    },
  },
}
```

**Review by gacallea — COMMENTED** [review]
seems to work just fine so far :)

**Comment by gacallea** [comment]
tested my local installation/config (like the above, with minor asthethics), and all seems fine. gtg :)

**Review by LostNeophyte — APPROVED** [review]
it's working, thanks :)

**Comment by vonPB** [comment]
@LostNeophyte feel free to merge if u think it works :)

**Pull request merged**
