### PR TITLE
docs(installation): don't exit powershell on error

### PR DESCRIPTION
**Pull request by LostNeophyte**
fixes an issue where powershell would exit if there are errors

### CODE REVIEW

**Comment by vonPB** [comment]
Results in this in my vm:
```ps
PS C:\Users\PC01> pwsh -c (iwr https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing).Content

# ignore this, do I do this on ps startup: Visual Studio 2022 Command Prompt variables set.
ParserError:
Line |
   5 |  $LV_BRANCH = $LV_BRANCH ?? master
     |                            ~
     | You must provide a value expression following the '??' operator.

```

**Comment by vonPB** [comment]
The old script works just fine

**Comment by LostNeophyte** [comment]
> The old command works just fine

Run it when you don't have `make` installed, it will close the terminal, it she's it for me at least

**Comment by LostNeophyte** [comment]
does this work? 
``pwsh -c "`$LV_BRANCH='release-1.2/neovim-0.8'; iwr https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | iex"``

``pwsh -c "iwr https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | iex"``

**Pull request merged**
