### PR TITLE
fixing lastplace module and adding commenting at the end of each module

### PR DESCRIPTION
**Pull request by gnmearacaun**
Following [the discussion](https://github.com/ChristianChiarulli/LunarVim/issues/616#issuecomment-890879802) on PR #616 now that the wiki has moved to lunarvim.org.
The is a request to fix the lastplace module and to add comments to each of the modules so that they are "plug and play".

### CODE REVIEW

**Comment by gnmearacaun** [comment]
Just realized, maybe tpope/unimpaired in the example table is redundant because we have autopairs? (I'm not sure)

**Comment by rebuilt** [comment]
Unimpaired is probably not the best example.  Can you pick something from this list please https://github.com/rockerBOO/awesome-neovim. Also, yes those commas are pretty useful, thanks.

**Comment by rebuilt** [comment]
As far as dividing commits, it makes things easier to approve and deny selectivity but it's not a deal breaker.  For code it's much more important but for plain text, it's not a big deal.  That said,  I can't merge this till you change the example.

**Comment by rebuilt** [comment]
Thank you very much!

**Comment by gnmearacaun** [comment]
Beautiful, thanks!

**Pull request merged**
